### ISSUE TITLE
blade-cli is really slow while performing raster scan

### ISSUE THREAD

**Issue by savinshynu** [COSMIC-SETI/FrontPage#7]
Trying to form a raster beam around voyager source with this command:
blade-cli --input-type CI8 --output-type F32  -m B  -c 131072 -C 1 -T 70 -N 1 -t ATA /mnt/buf1/voyager2/TCOS0001.sb43831462.eb43831531.60060.2801225463.4.1.BD.C480  voyager_raster_bd.bfr5 outfil_bd_raster/

1.  First of all the raster bfr5 has 70 beams and -T cannot be less than number of beams, otherwise code will fail. Not sure why those 2 numbers are coupled. If T > nbeams, it for eg. 80 it is showing cuda allocation error
2. When I double the channelization or c. there is a cuda allocation error. how does the channelization affects memory. Anyway we are reading the single channel data across time into memory first and then doing all the FFT right.
3. The code should not be working for some magic numbers.
4. If I am reading all guppy raw files. the code takes 12 days to run. Or if I'm taking the first 5 files, it is showing 3 days.
5. Is this how it suppose to be?

**Comment by radonnachie** [comment]
Are you writing out to a local NVMe as well, that may be the only thing one could do to ensure optimal performance.

**Comment by savinshynu** [comment]
No, I am writing filter bank files to a  /mnt/slow/. But would that make a big difference?

**Comment by savinshynu** [comment]
Writing to NVME is shows  1 day and 16 hours. Run time decreased by half. That's good.

**Comment by Chenoachem** [comment]
@savinshynu do you still see this as an issue?

**Comment by savinshynu** [comment]
@Chenoa Tremblay ***@***.***> I think it was fixed a long time
ago.

-Savin
